name: Data Schema Code Convention (SQL)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  SQLLinter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code in Repository
        uses: actions/checkout@v3

      - name: Install SQL Linter (sqlfluff)
        run: python -m pip install sqlfluff

      - name: Validate DataSchema.sql
        run: sqlfluff lint "$GITHUB_WORKSPACE/2-SoftwareDesign/2.4-PhysicalSchema/DataSchema.sql" --dialect postgres

      - name: Validate DataSchemaModified
        run: sqlfluff lint "$GITHUB_WORKSPACE/2-SoftwareDesign/2.4-PhysicalSchema/DataSchemaModified" --dialect postgres
