name: Print software versions

on:
  workflow_dispatch:

jobs:
  processing_level:
    name: Data processing level software versions
    runs-on: ubuntu-latest
    steps:
      - name: Print OS version
        run: |
          uname -a
          lsb_release -a || cat /etc/os-release
      - name: Print Docker version
        run: docker --version

  data_access_level:
    name: Data access level DBMS version
    runs-on: ubuntu-latest
    steps:
      - name: Print PostgreSQL 16 version
        run: docker run --rm postgres:16-alpine postgres --version
