name: Program Code Convention (Python)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  PythonLinter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code in Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install Python Linter (flake8)
        run: pip install flake8

      - name: Validate program code
        run: flake8 $GITHUB_WORKSPACE/ProgramCodeModified.py

